name: Workflow dispatch

on:
  workflow_dispatch:

jobs:
  run:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: echo "Hello World"
      
    - name: Enviroment Variables
      env: 
        CURRENT_DATE: '2024-20-26'
      run: |
        echo "CURRENT_DATE": $CURRENT_DATE"
        echo 'Linux date: $(date)"
        echo "Github context date: ${{github.event.repository.pushed_at}}"

    - name: Dump GitHub context
      env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: List directory content
      run: ls -al

    - name: Checkout
      uses: actions/checkout@v4

    - name: List directory content
      run: ls -al

    - name: List enviroment variable
      run: env

    - name: List processes
      run: ps aux

    - uses: actions/setup-python@v5
      with:
       python-version: '3.12' 

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Generate report
      run: python run-report.py

      


    


    



  

     
